### ISSUE TITLE
File not uploading to google drive

### ISSUE THREAD

**Issue by SGR007** [SlamDevs/slam-mirrorbot#395]
2021-09-10T09:28:51.114563+00:00 app[web.1]: [2021-09-10 09:28:51 +0000] [19] [INFO] Booting worker with pid: 19
2021-09-10T09:28:52.043888+00:00 app[web.1]: 2021-09-10 09:28:52,043 - bot - INFO - Generating USER_SESSION_STRING
2021-09-10T09:28:52.045042+00:00 app[web.1]: 2021-09-10 09:28:52,044 - bot - INFO - Generating TELEGRAPH_TOKEN using 'WVlWljel' name
2021-09-10T09:28:52.370746+00:00 app[web.1]: 2021-09-10 09:28:52,370 - root - WARNING - MEGA Credentials not provided!
2021-09-10T09:28:52.617934+00:00 heroku[web.1]: State changed from starting to up
2021-09-10T09:28:55.241753+00:00 app[web.1]: Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
2021-09-10T09:28:55.241767+00:00 app[web.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
2021-09-10T09:28:55.241768+00:00 app[web.1]: 
2021-09-10T09:28:59.728979+00:00 app[web.1]: 2021-09-10 09:28:59,728 - apscheduler.scheduler - INFO - Scheduler started
2021-09-10T09:28:59.818497+00:00 app[web.1]: 2021-09-10 09:28:59,818 - bot - INFO - Bot Started!
2021-09-10T09:29:48.386853+00:00 app[web.1]: 2021-09-10 09:29:48,386 - bot - INFO - https://download.manjaro.org/i3/21.1.2/manjaro-i3-21.1.2-210907-linux513.iso
2021-09-10T09:29:48.387529+00:00 app[web.1]: 2021-09-10 09:29:48,387 - bot - INFO - No Direct link function found for https://download.manjaro.org/i3/21.1.2/manjaro-i3-21.1.2-210907-linux513.iso
2021-09-10T09:29:48.400209+00:00 app[web.1]: 2021-09-10 09:29:48,400 - bot - INFO - Started: 905d285c505b8c34 DIR:/usr/src/app/downloads/448 
2021-09-10T09:30:30.537020+00:00 app[web.1]: 2021-09-10 09:30:30,536 - bot - INFO - Download completed: manjaro-i3-21.1.2-210907-linux513.iso
2021-09-10T09:30:30.545416+00:00 app[web.1]: 2021-09-10 09:30:30,545 - bot - INFO - Upload Name: manjaro-i3-21.1.2-210907-linux513.iso
2021-09-10T09:30:30.675569+00:00 app[web.1]: Exception in thread Thread-4:
2021-09-10T09:30:30.675589+00:00 app[web.1]: Traceback (most recent call last):
2021-09-10T09:30:30.675603+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-09-10T09:30:30.675916+00:00 app[web.1]:     self.run()
2021-09-10T09:30:30.675934+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 870, in run
2021-09-10T09:30:30.676175+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2021-09-10T09:30:30.676191+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror.py", line 114, in onDownloadComplete
2021-09-10T09:30:30.676328+00:00 app[web.1]:     drive = gdriveTools.GoogleDriveHelper(up_name, self)
2021-09-10T09:30:30.676353+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 53, in __init__
2021-09-10T09:30:30.676478+00:00 app[web.1]:     self.__service = self.authorize()
2021-09-10T09:30:30.676500+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 557, in authorize
2021-09-10T09:30:30.676818+00:00 app[web.1]:     credentials.refresh(Request())
2021-09-10T09:30:30.676843+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/google/oauth2/credentials.py", line 291, in refresh
2021-09-10T09:30:30.677100+00:00 app[web.1]:     ) = reauth.refresh_grant(
2021-09-10T09:30:30.677124+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/google/oauth2/reauth.py", line 336, in refresh_grant
2021-09-10T09:30:30.677362+00:00 app[web.1]:     _client._handle_error_response(response_data)
2021-09-10T09:30:30.677387+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/google/oauth2/_client.py", line 58, in _handle_error_response
2021-09-10T09:30:30.677563+00:00 app[web.1]:     raise exceptions.RefreshError(error_details, response_data)
2021-09-10T09:30:30.677719+00:00 app[web.1]: google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})

getting this error

**Comment by breakdowns** [comment]
The log already clear. **Token has been expired or revoked**

**Comment by SGR007** [comment]
> The log already clear. **Token has been expired or revoked**
> 
> **SOLUTION**: Regenerate token.pickle.

Yes, i tried i am getting the same error

> python generate_drive_token.py
Traceback (most recent call last):
  File ".\generate_drive_token.py", line 18, in <module>
    credentials.refresh(Request())
  File "E:\Git\Python\slam-mirrorbot\venv\lib\site-packages\google\oauth2\credentials.py", line 291, in refresh  
    ) = reauth.refresh_grant(
  File "E:\Git\Python\slam-mirrorbot\venv\lib\site-packages\google\oauth2\reauth.py", line 336, in refresh_grant 
    _client._handle_error_response(response_data)
  File "E:\Git\Python\slam-mirrorbot\venv\lib\site-packages\google\oauth2\_client.py", line 58, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})

**Comment by SGR007** [comment]
> > The log already clear. **Token has been expired or revoked**
> > **SOLUTION**: Regenerate token.pickle.
> 
> Yes, i tried i am getting the same error
> 
> > python generate_drive_token.py
> > Traceback (most recent call last):
> > File ".\generate_drive_token.py", line 18, in 
> > credentials.refresh(Request())
> > File "E:\Git\Python\slam-mirrorbot\venv\lib\site-packages\google\oauth2\credentials.py", line 291, in refresh
> > ) = reauth.refresh_grant(
> > File "E:\Git\Python\slam-mirrorbot\venv\lib\site-packages\google\oauth2\reauth.py", line 336, in refresh_grant
> > _client._handle_error_response(response_data)
> > File "E:\Git\Python\slam-mirrorbot\venv\lib\site-packages\google\oauth2_client.py", line 58, in _handle_error_response
> > raise exceptions.RefreshError(error_details, response_data)
> > google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})



> The log already clear. **Token has been expired or revoked**
> 
> **SOLUTION**: Regenerate token.pickle.

Solved
