### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by raspy00** [SlamDevs/slam-mirrorbot#397]
2021-09-11T14:55:20.884983+00:00 app[web.1]: 2021-09-11 14:55:20,884 - bot - INFO - magnet:?xt=urn:btih:C642DD448D6C3DBEEAD5BE37966B94AB2DDDF47A&dn=Rick.and.Morty.S05E10.1080p.WEBRip.x264-CAKES&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2870%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2840%2Fannounce&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13710%2Fannounce&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15710%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce
2021-09-11T14:55:20.918683+00:00 app[web.1]: 2021-09-11 14:55:20,918 - bot - INFO - Started: f4dcbd3a6fb6fbbc DIR:/usr/src/app/downloads/12 
2021-09-11T14:55:21.926843+00:00 app[web.1]: 2021-09-11 14:55:21,926 - bot - INFO - Checking File/Folder if already in Drive...
2021-09-11T14:55:21.936154+00:00 app[web.1]: Exception in thread Thread-97:
2021-09-11T14:55:21.936183+00:00 app[web.1]: Traceback (most recent call last):
2021-09-11T14:55:21.936208+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-09-11T14:55:21.936567+00:00 app[web.1]:     self.run()
2021-09-11T14:55:21.936584+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 870, in run
2021-09-11T14:55:21.936817+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2021-09-11T14:55:21.936832+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/aria2_download.py", line 32, in __onDownloadStarted
2021-09-11T14:55:21.936923+00:00 app[web.1]:     gdrive = GoogleDriveHelper()
2021-09-11T14:55:21.936937+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 53, in __init__
2021-09-11T14:55:21.937022+00:00 app[web.1]:     self.__service = self.authorize()
2021-09-11T14:55:21.937033+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 554, in authorize
2021-09-11T14:55:21.937206+00:00 app[web.1]:     credentials = pickle.load(f)
2021-09-11T14:55:21.937259+00:00 app[web.1]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)
2021-09-11T14:59:20.015220+00:00 app[web.1]: 2021-09-11 14:59:20,015 - bot - INFO - Changed gid from f4dcbd3a6fb6fbbc to d40a5824710910b8
2021-09-11T14:59:21.088707+00:00 app[web.1]: 2021-09-11 14:59:21,088 - bot - INFO - Checking File/Folder if already in Drive...
2021-09-11T14:59:21.098227+00:00 app[web.1]: Exception in thread Thread-99:
2021-09-11T14:59:21.098237+00:00 app[web.1]: Traceback (most recent call last):
2021-09-11T14:59:21.098252+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-09-11T14:59:21.098469+00:00 app[web.1]:     self.run()
2021-09-11T14:59:21.098483+00:00 app[web.1]:   File "/usr/lib/python3.8/threading.py", line 870, in run
2021-09-11T14:59:21.098656+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2021-09-11T14:59:21.098673+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/download_utils/aria2_download.py", line 32, in __onDownloadStarted
2021-09-11T14:59:21.098757+00:00 app[web.1]:     gdrive = GoogleDriveHelper()
2021-09-11T14:59:21.098772+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 53, in __init__
2021-09-11T14:59:21.098851+00:00 app[web.1]:     self.__service = self.authorize()
2021-09-11T14:59:21.098866+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 554, in authorize
2021-09-11T14:59:21.099048+00:00 app[web.1]:     credentials = pickle.load(f)
2021-09-11T14:59:21.099095+00:00 app[web.1]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)

**Comment by anasty17** [comment]
Ask in support group
