### ISSUE TITLE
Got error when starting bot

### ISSUE THREAD

**Issue by dracu52** [SlamDevs/slam-mirrorbot#402]
[2021-09-13 06:56:24 +0000] [20] [INFO] Starting gunicorn 20.1.0
[2021-09-13 06:56:24 +0000] [20] [INFO] Listening at: http://0.0.0.0:80 (20)
[2021-09-13 06:56:24 +0000] [20] [INFO] Using worker: aiohttp.GunicornWebWorker
[2021-09-13 06:56:24 +0000] [22] [INFO] Booting worker with pid: 22
2021-09-13 06:56:25,385 - bot - INFO - Generating USER_SESSION_STRING
2021-09-13 06:56:25,386 - bot - INFO - Generating TELEGRAPH_TOKEN using 'jnwshGMa' name
Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 255, in <module>
    main()
  File "/usr/src/app/bot/__main__.py", line 211, in main
    asyncio.get_event_loop().run_until_complete(start_server_async(PORT))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/src/app/wserver.py", line 740, in start_server_async
    await web.TCPSite(runner, "0.0.0.0", port).start()
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 80): address already in use

![error](https://user-images.githubusercontent.com/88800551/133038005-45024074-47b2-4b7d-a9d2-1d4e16bfd889.PNG)

**Comment by anasty17** [comment]
@dracu52 Is vps true or false ?

**Comment by anasty17** [comment]
@dracu52 It's true ... check readme then open issue plz
